application: youtify
version: 12
runtime: python
api_version: 1

error_handlers:
  - file: html/error.html

  - error_code: over_quota
    file: html/quota.html

handlers:

- url: /me.*
  script: me.py

- url: /api/users.*
  script: users.py

- url: /export
  static_files: html/export.html
  upload: html/export.html
  expiration: "1d"

- url: /import
  static_files: html/import.html
  upload: html/import.html
  expiration: "1d"

- url: /about
  static_files: html/popups/about.html
  upload: html/popups/about.html
  #expiration: "1d"

- url: /test.*
  script: gaeunit.py
  login: admin

- url: /jstests
  static_files: html/tests.html
  upload: html/tests.html
  login: admin

- url: /filter
  static_files: html/filter.html
  upload: html/filter.html
  login: admin

- url: /minimizer
  script: minimizer.py
  login: admin

- url: /your.*
  script: sucks.py

- url: /toplist.*
  script: toplist.py

- url: /flattr_toplist.*
  script: flattr_toplist.py

- url: /flattr_submit.*
  script: flattr_submit.py

- url: /api/playlists.*
  script: playlists.py

- url: /pingcron
  script: ping.py
  login: admin

- url: /pinggraph
  script: ping.py
  login: admin

- url: /ping.*
  script: ping.py

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images
  expiration: "1d"

- url: /import_old_translations
  script: import_old_translations.py
  login: admin

- url: /admin.*
  script: admin.py
  login: admin

- url: /translations.*
  script: translations.py
  login: required

- url: /phrases.*
  script: phrases.py

- url: /languages.*
  script: languages.py

- url: /snapshots.*
  script: snapshots.py

- url: /api/translations/.*
  script: snapshots.py
  
- url: /robots.*
  static_files: robots.txt
  upload: robots.txt
  expiration: "1d"

- url: /flattr.*
  script: flattr.py
  login: required

- url: /.*
  script: main.py

