application: youtify
version: 1
runtime: python
api_version: 1

error_handlers:
  - file: html/error.html

  - error_code: over_quota
    file: html/quota.html

handlers:

- url: /export
  static_files: html/export.html
  upload: html/export.html

- url: /import
  static_files: html/import.html
  upload: html/import.html

- url: /tests
  static_files: html/tests.html
  upload: html/tests.html
  login: admin

- url: /beta
  script: beta.py

- url: /your.*
  script: sucks.py

- url: /toplist.*
  script: toplist.py

- url: /playlists.*
  script: playlists.py

- url: /pingcron
  script: ping.py
  login: admin

- url: /pinggraph
  script: ping.py
  login: admin

- url: /ping.*
  script: ping.py

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /translations.*
  script: translations.py
  
- url: /robots.*
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.py

