application: youtify
version: 1
runtime: python
api_version: 1

error_handlers:
  - file: html/error.html

  - error_code: over_quota
    file: html/quota.html

handlers:

- url: /export
  static_files: html/export.html
  upload: html/export.html
  expiration: "1d"

- url: /import
  static_files: html/import.html
  upload: html/import.html
  expiration: "1d"

- url: /heart
  static_files: html/popups/heart.html
  upload: html/popups/heart.html
  expiration: "1d"

- url: /test.*
  script: gaeunit.py
  login: admin

- url: /jstests
  static_files: html/tests.html
  upload: html/tests.html
  login: admin

- url: /minimizer
  script: minimizer.py
  login: admin

- url: /your.*
  script: sucks.py

- url: /toplist.*
  script: toplist.py

- url: /api/playlists.*
  script: playlists.py

- url: /pingcron
  script: ping.py
  login: admin

- url: /pinggraph
  script: ping.py
  login: admin

- url: /ping.*
  script: ping.py

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images
  expiration: "1d"

- url: /translations.*
  script: translations.py
  
- url: /robots.*
  static_files: robots.txt
  upload: robots.txt
  expiration: "1d"

- url: /.*
  script: main.py

